export const ADD_CUSTOMER_DETAILS_REQUEST = "ADD_CUSTOMER_DETAILS_REQUEST";
export const ADD_CUSTOMER_DETAILS_SUCCESS = "ADD_CUSTOMER_DETAILS_SUCCESS";
export const ADD_CUSTOMER_DETAILS_FAILURE = "ADD_CUSTOMER_DETAILS_FAILURE";

export const DELETE_CUSTOMER_DETAILS_REQUEST = "DELETE_CUSTOMER_DETAILS_REQUEST";
export const DELETE_CUSTOMER_DETAILS_SUCCESS = "DELETE_CUSTOMER_DETAILS_SUCCESS";
export const DELETE_CUSTOMER_DETAILS_FAILURE = "DELETE_CUSTOMER_DETAILS_FAILURE";

export const GET_ALL_CUSTOMER_REQUEST = "GET_ALL_CUSTOMER_REQUEST";
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER_FAILURE = "GET_ALL_CUSTOMER_FAILURE";

export const EDIT_CUSTOMER_DATA_REQUEST = "EDIT_CUSTOMER_DATA_REQUEST";
export const EDIT_CUSTOMER_DATA_SUCCESS = "EDIT_CUSTOMER_DATA_SUCCESS";
export const EDIT_CUSTOMER_DATA_FAILURE = "EDIT_CUSTOMER_DATA_FAILURE";
